(require 'tui-button "components/tui-button.el")
(require 'tui-buffer "components/tui-buffer.el")
(require 'tui-div "components/tui-div.el")
(require 'tui-expander "components/tui-expander.el")
(require 'tui-fixed-width "components/tui-fixed-width.el")
(require 'tui-heading "components/tui-heading.el")
(require 'tui-icon "components/tui-icon.el")
(require 'tui-line "components/tui-line.el")
(require 'tui-link "components/tui-link.el")
(require 'tui-ol "components/tui-ol.el")
(require 'tui-ul "components/tui-ul.el")
(require 'tui-span "components/tui-span.el")
(require 'tui-spinner "components/tui-spinner.el")
(require 'tui-timer "components/tui-timer.el")
(require 'tui-prefix-lines "components/tui-prefix-lines.el")

(provide 'tui-components)
